xymatic.settings:
  type: config_object
  label: 'Xymatic settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
    api_url:
      type: string
      label: 'API URL'
    license_key:
      type: string
      label: 'License Key'
    access_token:
      type: string
      label: 'Access token'
    media_type:
      type: string
      label: 'Media type'

media.source.xymatic:
  type: media.source.field_aware
  label: '"Xymatic" media source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'
